CC=gcc

ifndef OBJ_DIR
$(error please define OBJ_DIR)
endif

ifndef DST_DIR
$(error please define DST_DIR)
endif

CXXFLAGS = \
	-DENABLE_TRACE \
	-O2 \
	-Wall \
	-Wextra \
	-Wno-parentheses \
	-Wshadow \
	-Wunreachable-code \
	-g \
	-std=c++17

ifdef DEBUG
	CXXFLAGS +=  \
		-fsanitize=address
endif

LDFLAGS = \
	-lstdc++

ifdef DEBUG
	LDFLAGS += \
		-fsanitize=address
endif
