name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get -y install nlohmann-json3-dev
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build
      run: make
